### PR TITLE
Changing the code to use local mapping file instead of using remote api to chinesecj.com

### PR DESCRIPTION
**Pull request by tomasgodoicd**
Like stated on https://github.com/geniusgordon/cangjie-code/issues/7, the website chinesecj.com is not working properly, so I changed the way the progam converts a character to the code. I'm using now a mapping table file found at https://github.com/acevery/ibus-table-cangjie/blob/master/tables/cangjie5.txt, which claims to be an extraction of the chinesecj.com data.
The advantage of this approach is twofold: the program doesn't need the site to be online for it to work and it will run faster for batch conversions.

### CODE REVIEW

**Comment by geniusgordon** [comment]
Looks great! Thanks for your work!
How about separating codes with commas if there's more than one, like '資': '戈人月山金, 一人月山金'

**Comment by tomasgodoicd** [comment]
@geniusgordon That's a great suggestion! It would also be nice to allow to convert to the equivalent latin alphabet codes.

**Comment by geniusgordon** [comment]
Maybe we should change the api and return more information instead of only return { word: 'code' }
I think we can do that in another branch.

**Comment by geniusgordon** [comment]
I think I can merge this first

**Pull request merged**
